;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(evil-want-Y-yank-to-eol nil)
 '(exec-path
   (quote
    ("c:/Program Files/Basler/pylon 5/Runtime/Win32" "c:/Program Files/Basler/pylon 5/Runtime/x64" "c:/Program Files (x86)/Common Files/Oracle/Java/javapath" "c:/Program Files/Common Files/Siemens/Automation/Simatic OAM/bin" "d:/Program Files/Python37/Scripts" "d:/Program Files/Python37" "c:/Windows/system32" "c:/Windows" "c:/Windows/System32/Wbem" "c:/Windows/System32/WindowsPowerShell/v1.0" "c:/Program Files/dotnet" "c:/LLVM/bin" "d:/Program Files (x86)/GnuWin32/bin" "e:/Qt/Qt5.12.0/Tools/mingw730_64/bin" "e:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin" "d:/Program Files (x86)/ForceControl V7.0" "d:/Program Files/CMake/bin" "c:/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn" "c:/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn" "c:/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn" "d:/Program Files (x86)/sqlite3" "d:/Program Files/ALTRun" "e:/swords/routine" "c:/Orion/idsvision_v1.0/bin" "c:/Orion/idsvision_v1.0/opencv/bin" "c:/Orion/idsvision_v1.0/openvx/bin" "c:/Orion/idsvision_v1.0/openvino/bin/intel64/Release" "d:/Program Files/nodejs" "c:/Program Files/MiKTeX 2.9/miktex/bin/x64" "c:/ProgramData/chocolatey/bin" "c:/Program Files/Git/cmd" "d:/Cadence/Cadence_SPB_16.6/openaccess/bin/win32/opt" "d:/Cadence/Cadence_SPB_16.6/tools/capture" "d:/Cadence/Cadence_SPB_16.6/tools/pspice" "d:/Cadence/Cadence_SPB_16.6/tools/specctra/bin" "d:/Cadence/Cadence_SPB_16.6/tools/fet/bin" "d:/Cadence/Cadence_SPB_16.6/tools/libutil/bin" "d:/Cadence/Cadence_SPB_16.6/tools/bin" "d:/Cadence/Cadence_SPB_16.6/tools/pcb/bin" "d:/Program Files/Microsoft VS Code/bin" "c:/Users/mp/AppData/Roaming/npm" "h:/emacs-26.3-x86_64/libexec/emacs/26.3/x86_64-w64-mingw32" "c:/Program Files/Git/usr/bin" "c:/Program Files/gnuplot/bin")))
 '(magit-diff-use-overlays nil)
 '(org-agenda-files (quote ("D:\\Cadence\\SPB_Data\\mydocs\\org")))
 '(org-default-notes-file "d:/Cadence/SPB_Data/mydocs/org/notes.org" t)
 '(package-selected-packages
   (quote
    (powershell helm-ctest cmake-mode cmake-ide levenshtein lsp-ui lsp-treemacs helm-rtags helm-lsp flycheck-rtags cquery company-rtags company-lsp ccls google-c-style flycheck-ycmd disaster cpp-auto-include company-ycmd ycmd request-deferred deferred rtags company-c-headers clang-format lsp-mode dash-functional x86-lookup nasm-mode youdao-dictionary names chinese-word-at-point ahk-mode org-sticky-header org-journal xterm-color ws-butler winum which-key volatile-highlights vi-tilde-fringe uuidgen use-package unfill toc-org spaceline powerline smeargle shell-pop restart-emacs rainbow-delimiters popwin persp-mode pcre2el paradox spinner orgit org-projectile org-category-capture org-present org-pomodoro alert log4e gntp org-plus-contrib org-mime org-download org-bullets open-junk-file neotree mwim multi-term move-text mmm-mode markdown-toc markdown-mode magit-gitflow magit-popup macrostep lorem-ipsum linum-relative link-hint indent-guide hydra lv hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers parent-mode highlight-indentation helm-themes helm-swoop helm-projectile projectile pkg-info epl helm-mode-manager helm-make helm-gitignore request helm-flx helm-descbinds helm-company helm-c-yasnippet helm-ag google-translate golden-ratio gnuplot gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gh-md fuzzy flx-ido flx fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist highlight evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit magit transient git-commit with-editor evil-lisp-state smartparens evil-indent-plus evil-iedit-state iedit evil-exchange evil-escape evil-ediff evil-args evil-anzu anzu evil goto-chg undo-tree eval-sexp-fu eshell-z eshell-prompt-extras esh-help elisp-slime-nav dumb-jump f dash s diminish define-word company-statistics company column-enforce-mode clean-aindent-mode bind-map bind-key auto-yasnippet yasnippet auto-highlight-symbol auto-compile packed aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line helm avy helm-core async ac-ispell auto-complete popup))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
